"""tip_number_nullable

Revision ID: 3e1ebb1401dc
Revises: k1l2m3n4o5p6
Create Date: 2026-03-07 17:32:57.213323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1ebb1401dc'
down_revision = 'k1l2m3n4o5p6'
branch_labels = None
depends_on = None


def upgrade():
    # Make tip_number optional
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tip_number',
               existing_type=sa.String(length=20),
               nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osint_contact_type_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_osint_contact_type_configs_type_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_osint_contact_type_configs_type_key'))
        batch_op.create_index(batch_op.f('ix_osint_contact_type_configs_type_key'), ['type_key'], unique=True)
        batch_op.drop_constraint(batch_op.f('osint_contact_type_configs_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('include_osint_contacts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # Restore tip_number as non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tip_number',
               existing_type=sa.String(length=20),
               nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('include_osint_contacts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('osint_contact_type_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('osint_contact_type_configs_created_by_id_fkey'), 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_osint_contact_type_configs_type_key'))
        batch_op.create_index(batch_op.f('ix_osint_contact_type_configs_type_key'), ['type_key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_osint_contact_type_configs_type_key'), ['type_key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
