"""initial_schema

Revision ID: 936860c27134
Revises: 
Create Date: 2026-05-23 05:34:26.607914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '936860c27134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=True),
    sa.Column('tip_number', sa.String(length=20), nullable=True),
    sa.Column('despacho', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tip_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('key_name', sa.String(length=200), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_service_name'), ['service_name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp_signature', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('legitimacy_types_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legal_reference', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legitimacy_types_custom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legitimacy_types_custom_name'), ['name'], unique=True)

    op.create_table('osint_contact_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osint_contact_type_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osint_contact_type_configs_type_key'), ['type_key'], unique=True)

    op.create_table('relationship_types_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship_types_custom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_types_custom_name'), ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('cliente_dni_cif', sa.String(length=20), nullable=False),
    sa.Column('cliente_direccion', sa.Text(), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('legitimacy_type', sa.Enum('BAJAS_LABORALES', 'COMPETENCIA_DESLEAL', 'CUSTODIA_MENORES', 'INVESTIGACION_PATRIMONIAL', 'FRAUDE_SEGUROS', 'INFIDELIDAD_CONYUGAL', 'LOCALIZACION_PERSONAS', 'SOLVENCIA_PATRIMONIAL', 'OTROS', name='legitimacytype'), nullable=True),
    sa.Column('legitimacy_type_custom_id', sa.Integer(), nullable=True),
    sa.Column('legitimacy_document_path', sa.String(length=500), nullable=True),
    sa.Column('legitimacy_description', sa.Text(), nullable=False),
    sa.Column('legitimacy_validated', sa.Boolean(), nullable=False),
    sa.Column('legitimacy_validated_by_id', sa.Integer(), nullable=True),
    sa.Column('legitimacy_validated_at', sa.DateTime(), nullable=True),
    sa.Column('sujeto_nombres', sa.Text(), nullable=True),
    sa.Column('sujeto_dni_nie', sa.Text(), nullable=True),
    sa.Column('sujeto_descripcion', sa.Text(), nullable=True),
    sa.Column('objeto_investigacion', sa.Text(), nullable=False),
    sa.Column('descripcion_detallada', sa.Text(), nullable=True),
    sa.Column('detective_id', sa.Integer(), nullable=False),
    sa.Column('detective_tip', sa.String(length=20), nullable=False),
    sa.Column('despacho', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE_VALIDACION', 'EN_INVESTIGACION', 'SUSPENDIDO', 'CERRADO', 'ARCHIVADO', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='casepriority'), nullable=True),
    sa.Column('crime_detected', sa.Boolean(), nullable=True),
    sa.Column('crime_keywords_found', sa.Text(), nullable=True),
    sa.Column('crime_description', sa.Text(), nullable=True),
    sa.Column('crime_reported', sa.Boolean(), nullable=True),
    sa.Column('crime_reported_at', sa.DateTime(), nullable=True),
    sa.Column('crime_reported_to', sa.String(length=200), nullable=True),
    sa.Column('confidencial', sa.Boolean(), nullable=False),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('ubicacion_principal', sa.String(length=500), nullable=True),
    sa.Column('presupuesto_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('honorarios', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detective_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legitimacy_type_custom_id'], ['legitimacy_types_custom.id'], ),
    sa.ForeignKeyConstraint(['legitimacy_validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_numero_orden'), ['numero_orden'], unique=True)

    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.Enum('IMAGEN', 'VIDEO', 'AUDIO', 'DOCUMENTO', 'CAPTURA_WEB', 'DATOS_DIGITALES', 'EMAIL', 'OTROS', name='evidencetype'), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('sha512_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trusted_timestamp', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=True),
    sa.Column('encryption_nonce', sa.String(length=24), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('acquisition_method', sa.String(length=200), nullable=True),
    sa.Column('acquisition_tool', sa.String(length=200), nullable=True),
    sa.Column('acquisition_notes', sa.Text(), nullable=True),
    sa.Column('source_device', sa.String(length=200), nullable=True),
    sa.Column('source_location', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('neo4j_node_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('integrity_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verification_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('graph_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('monitoring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monitoring_objective', sa.Text(), nullable=False),
    sa.Column('ai_provider', sa.Enum('DEEPSEEK', 'OPENAI', name='aiprovider'), nullable=False),
    sa.Column('ai_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_prompt_template', sa.Text(), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='monitoringstatus'), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('alerts_count', sa.Integer(), nullable=False),
    sa.Column('unread_alerts_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_tasks_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_tasks_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_tasks_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_tasks_status'), ['status'], unique=False)

    op.create_table('osint_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('email', 'phone', name='contact_type_enum'), nullable=False),
    sa.Column('contact_value', sa.String(length=200), nullable=False),
    sa.Column('validation_date', sa.DateTime(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osint_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osint_validations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_validations_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_validations_contact_value'), ['contact_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_validations_validation_date'), ['validation_date'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('INFORME_FINAL', 'INFORME_PARCIAL', 'INFORME_PRELIMINAR', 'DICTAMEN_PERICIAL', 'ANEXO_TECNICO', name='reporttype'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('conclusions', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('include_evidence_list', sa.Boolean(), nullable=True),
    sa.Column('include_timeline', sa.Boolean(), nullable=True),
    sa.Column('include_graph', sa.Boolean(), nullable=True),
    sa.Column('include_chain_of_custody', sa.Boolean(), nullable=True),
    sa.Column('include_plugin_results', sa.Boolean(), nullable=True),
    sa.Column('include_evidence_thumbnails', sa.Boolean(), nullable=True),
    sa.Column('include_osint_contacts', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_hash_sha512', sa.String(length=128), nullable=True),
    sa.Column('docx_file_path', sa.String(length=500), nullable=True),
    sa.Column('docx_file_size', sa.Integer(), nullable=True),
    sa.Column('docx_file_hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('docx_file_hash_sha512', sa.String(length=128), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signature_timestamp', sa.DateTime(), nullable=True),
    sa.Column('signer_name', sa.String(length=200), nullable=True),
    sa.Column('signer_tip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'COMPLETED', 'FAILED', 'SIGNED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_report_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_of_custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('hash_verified', sa.Boolean(), nullable=True),
    sa.Column('hash_match', sa.Boolean(), nullable=True),
    sa.Column('sha256_calculated', sa.String(length=64), nullable=True),
    sa.Column('sha512_calculated', sa.String(length=128), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp_signature', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_of_custody', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_of_custody_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_chain_of_custody_timestamp'), ['timestamp'], unique=False)

    op.create_table('evidence_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('plugin_version', sa.String(length=20), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_by_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_analyses_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_analyses_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('monitoring_check_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('check_started_at', sa.DateTime(), nullable=False),
    sa.Column('check_completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('new_results_count', sa.Integer(), nullable=False),
    sa.Column('ai_analyses_count', sa.Integer(), nullable=False),
    sa.Column('alerts_generated', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['monitoring_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_check_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_check_logs_check_started_at'), ['check_started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_check_logs_task_id'), ['task_id'], unique=False)

    op.create_table('monitoring_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('X_TWITTER', 'INSTAGRAM', 'WEB_SEARCH', name='sourceplatform'), nullable=False),
    sa.Column('query_type', sa.Enum('USER_PROFILE', 'HASHTAG', 'SEARCH_QUERY', name='sourcequerytype'), nullable=False),
    sa.Column('query_value', sa.String(length=500), nullable=False),
    sa.Column('max_results_per_check', sa.Integer(), nullable=False),
    sa.Column('include_media', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_result_id', sa.String(length=200), nullable=True),
    sa.Column('last_result_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['monitoring_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_sources_task_id'), ['task_id'], unique=False)

    op.create_table('osint_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('contact_value', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_date', sa.DateTime(), nullable=True),
    sa.Column('validation_result_id', sa.Integer(), nullable=True),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'invalid', name='osint_contact_status_enum'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validation_result_id'], ['osint_validations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osint_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osint_contacts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_contacts_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_contacts_contact_value'), ['contact_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_contacts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_contacts_is_validated'), ['is_validated'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_contacts_status'), ['status'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('EVIDENCE_ACQUIRED', 'EVIDENCE_ANALYZED', 'OBSERVATION', 'SURVEILLANCE', 'LOCATION_SIGHTING', 'SUBJECT_ACTIVITY', 'MEETING', 'COMMUNICATION', 'VEHICLE_MOVEMENT', 'VEHICLE_SIGHTING', 'DIGITAL_ACTIVITY', 'SOCIAL_MEDIA_POST', 'CASE_OPENED', 'CASE_CLOSED', 'LEGITIMACY_VALIDATED', 'NOTE', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('subjects', sa.Text(), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_event_date'), ['event_date'], unique=False)

    op.create_table('monitoring_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('author_username', sa.String(length=200), nullable=True),
    sa.Column('author_display_name', sa.String(length=300), nullable=True),
    sa.Column('author_profile_url', sa.String(length=500), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('media_downloaded', sa.Boolean(), nullable=False),
    sa.Column('media_local_paths', sa.JSON(), nullable=True),
    sa.Column('media_hashes', sa.JSON(), nullable=True),
    sa.Column('media_base64', sa.JSON(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('ai_analyzed', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ai_provider_used', sa.String(length=50), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('ai_analysis_result', sa.JSON(), nullable=True),
    sa.Column('ai_relevance_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_flags', sa.JSON(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('alert_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('alert_acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('alert_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('alert_notes', sa.Text(), nullable=True),
    sa.Column('saved_as_evidence', sa.Boolean(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['alert_acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['monitoring_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['monitoring_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_results_ai_analyzed'), ['ai_analyzed'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_results_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_results_is_alert'), ['is_alert'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_results_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_results_source_timestamp'), ['source_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_results_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_results_task_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_results_source_timestamp'))
        batch_op.drop_index(batch_op.f('ix_monitoring_results_source_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_results_is_alert'))
        batch_op.drop_index(batch_op.f('ix_monitoring_results_external_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_results_ai_analyzed'))

    op.drop_table('monitoring_results')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_date'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('osint_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osint_contacts_status'))
        batch_op.drop_index(batch_op.f('ix_osint_contacts_is_validated'))
        batch_op.drop_index(batch_op.f('ix_osint_contacts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_osint_contacts_contact_value'))
        batch_op.drop_index(batch_op.f('ix_osint_contacts_contact_type'))
        batch_op.drop_index(batch_op.f('ix_osint_contacts_case_id'))

    op.drop_table('osint_contacts')
    with op.batch_alter_table('monitoring_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_sources_task_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_sources_is_active'))

    op.drop_table('monitoring_sources')
    with op.batch_alter_table('monitoring_check_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_check_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_check_logs_check_started_at'))

    op.drop_table('monitoring_check_logs')
    with op.batch_alter_table('evidence_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_analyses_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_analyses_analyzed_at'))

    op.drop_table('evidence_analyses')
    with op.batch_alter_table('chain_of_custody', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_of_custody_timestamp'))
        batch_op.drop_index(batch_op.f('ix_chain_of_custody_action'))

    op.drop_table('chain_of_custody')
    op.drop_table('reports')
    with op.batch_alter_table('osint_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osint_validations_validation_date'))
        batch_op.drop_index(batch_op.f('ix_osint_validations_contact_value'))
        batch_op.drop_index(batch_op.f('ix_osint_validations_contact_type'))
        batch_op.drop_index(batch_op.f('ix_osint_validations_case_id'))

    op.drop_table('osint_validations')
    with op.batch_alter_table('monitoring_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_monitoring_tasks_next_check_at'))
        batch_op.drop_index(batch_op.f('ix_monitoring_tasks_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_monitoring_tasks_case_id'))

    op.drop_table('monitoring_tasks')
    op.drop_table('graph_layouts')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_sha256_hash'))

    op.drop_table('evidences')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_numero_orden'))

    op.drop_table('cases')
    op.drop_table('user_roles')
    with op.batch_alter_table('relationship_types_custom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_types_custom_name'))

    op.drop_table('relationship_types_custom')
    with op.batch_alter_table('osint_contact_type_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osint_contact_type_configs_type_key'))

    op.drop_table('osint_contact_type_configs')
    with op.batch_alter_table('legitimacy_types_custom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legitimacy_types_custom_name'))

    op.drop_table('legitimacy_types_custom')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_service_name'))
        batch_op.drop_index(batch_op.f('ix_api_keys_is_active'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
