"""initial migration with all models including include_evidence_thumbnails

Revision ID: dda01fbc3d5e
Revises: f12d06e18f99
Create Date: 2026-01-10 16:41:56.198307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda01fbc3d5e'
down_revision = 'f12d06e18f99'
branch_labels = None
depends_on = None


def upgrade():
    """
    Add include_evidence_thumbnails column to reports table.

    This migration is conditional - it only adds the column if it doesn't already exist.
    This allows it to work for both:
    - Existing installations (adds the column)
    - New installations where f12d06e18f99 already created it (no-op)
    """
    # Check if column already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Get columns for reports table
    columns = [col['name'] for col in inspector.get_columns('reports')]

    # Only add column if it doesn't exist
    if 'include_evidence_thumbnails' not in columns:
        with op.batch_alter_table('reports', schema=None) as batch_op:
            batch_op.add_column(sa.Column('include_evidence_thumbnails', sa.Boolean(), nullable=True))

        # Set default value for existing rows
        op.execute("UPDATE reports SET include_evidence_thumbnails = false WHERE include_evidence_thumbnails IS NULL")

        # Make the column non-nullable with default
        with op.batch_alter_table('reports', schema=None) as batch_op:
            batch_op.alter_column('include_evidence_thumbnails', nullable=False, server_default='false')
    # If column already exists, do nothing (already created by f12d06e18f99 for new installations)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('include_evidence_thumbnails')

    # ### end Alembic commands ###
